"""empty message

Revision ID: 46d43ddca6dd
Revises: 56b1839e1559
Create Date: 2018-01-21 20:11:15.541070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d43ddca6dd'
down_revision = '56b1839e1559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miner', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_miner_mining_app_id'), ['mining_app_id', 'compatible_app_versions', 'currency_id', 'arguments_template'])

    with op.batch_alter_table('miningoperation', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_miningoperation_miner_id'), ['miner_id', 'mining_hardware_id', 'pool_id', 'wallet_id'])

    with op.batch_alter_table('operatingsystem', schema=None) as batch_op:
        batch_op.drop_constraint('uq_operatingsystem_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_operatingsystem_name'), ['name', 'version'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operatingsystem', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_operatingsystem_name'), type_='unique')
        batch_op.create_unique_constraint('uq_operatingsystem_name', ['name'])

    with op.batch_alter_table('miningoperation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_miningoperation_miner_id'), type_='unique')

    with op.batch_alter_table('miner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_miner_mining_app_id'), type_='unique')

    # ### end Alembic commands ###
