"""empty message

Revision ID: 56b1839e1559
Revises: b74a5815e135
Create Date: 2018-01-21 19:58:56.353886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b1839e1559'
down_revision = 'b74a5815e135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mininghardware', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_mininghardware_system_id'), ['system_id', 'id_on_system'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mininghardware', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_mininghardware_system_id'), type_='unique')

    # ### end Alembic commands ###
