"""empty message

Revision ID: 8cfbdb750232
Revises: 8e79bfba733d
Create Date: 2018-01-21 18:53:19.627529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfbdb750232'
down_revision = '8e79bfba733d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arguments_template', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('compatible_app_versions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('currency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_miner_currency_id_currency'), 'currency', ['currency_id'], ['id'])

    with op.batch_alter_table('mininghardware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_mininghardware_system_id_system'), 'system', ['system_id'], ['id'])

    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_system_os_id_operatingsystem'), 'operatingsystem', ['os_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_system_os_id_operatingsystem'), type_='foreignkey')
        batch_op.drop_column('os_id')

    with op.batch_alter_table('mininghardware', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mininghardware_system_id_system'), type_='foreignkey')
        batch_op.drop_column('system_id')

    with op.batch_alter_table('miner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_miner_currency_id_currency'), type_='foreignkey')
        batch_op.drop_column('currency_id')
        batch_op.drop_column('compatible_app_versions')
        batch_op.drop_column('arguments_template')

    # ### end Alembic commands ###
