"""empty message

Revision ID: 8e79bfba733d
Revises: c5fd558d2799
Create Date: 2018-01-19 15:24:58.308153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e79bfba733d'
down_revision = 'c5fd558d2799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
