"""empty message

Revision ID: b74a5815e135
Revises: 8cfbdb750232
Create Date: 2018-01-21 19:43:07.304531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74a5815e135'
down_revision = '8cfbdb750232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mininghardware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_on_system', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nature', sa.Enum('CPU', 'GPU', name='hardwarenatureenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mininghardware', schema=None) as batch_op:
        batch_op.drop_column('nature')
        batch_op.drop_column('id_on_system')

    # ### end Alembic commands ###
